### PR TITLE
[degiro] transaction log bug resolved (patch)

### LINKED ISSUE #1276: DeGiro
## Document
<details><summary>Call Nokia.pdf</summary><p>

```json
[
  [
    "Vgoa Wsksjl Jvgmjy",
    "Svüoqsqjy",
    "Dw Bsdngqo 6",
    "97033 Qzg Rsvlcabn",
    "Srheazrxayql:",
    "******Xhv",
    "(30556896)",
    "Transaktionsübersicht von 27-12-2020 bis 26-01-2021",
    "Datum",
    "Uhrzei",
    "t",
    "Produkt",
    "ISIN",
    "Referen",
    "zbörse",
    "Ausführungso",
    "rt",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährung",
    "Wert",
    "Wechse",
    "lkurs",
    "Transaktions",
    "kosten",
    "Gesamt",
    "26-01-2021",
    "14:54",
    "CALL 15.12.21 NOKIA 8",
    "DE000TR6T1W3",
    "FRA",
    "FRAB",
    "207",
    "0,48",
    "EUR",
    "-99,36",
    "EUR",
    "-99,36",
    "EUR",
    "-2,11",
    "EUR",
    "-101,47",
    "EUR",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "nwnrshhrofvlb@zdgfvs.ge",
    "I",
    "www.degiro.de",
    "Seite 1 /",
    "1",
    "Konto 2021-01-26"
  ]
]

```

</p></details>

## Community profile

https://community.tresor.one/u/5419facb

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #1284: Transaktionübersicht Degiro
## Document
<details><summary>Account.pdf</summary><p>

```json
[
  [
    "Dyue Mtdme Ifzb",
    "Ndjmcexfvgdrvhfpcb 36",
    "3170 Fükgnv",
    "Lbvblixbldq",
    "Jiqqjjlvnerg:",
    "******yaq",
    "(469094837)",
    "Kontoauszug von 01-11-2020 bis 26-01-2021",
    "Datum",
    "Uhrze",
    "Produkt",
    "Valutadatum",
    "ISIN",
    "Beschreibung",
    "Änderung",
    "Saldo",
    "FX",
    "26-01-2021",
    "12:03",
    "FUNDSHARE UCITS CHF CASH FUND",
    "25-01-2021",
    "NL0011280581",
    "Geldmarktfonds Umwandlung: Verkauf 79.7931 zu je 0.9764",
    "CHF",
    "CHF",
    "210.79",
    "25-01-2021",
    "16:15",
    "INVESCO ELWOOD GLOBAL BLOCKCHAIN",
    "UCIT...",
    "25-01-2021",
    "IE00BGBN6P67",
    "Währungswechsel (Einbuchung)",
    "EUR",
    "1'366.80",
    "EUR",
    "0.00",
    "0.9272",
    "25-01-2021",
    "16:15",
    "INVESCO ELWOOD GLOBAL BLOCKCHAIN",
    "UCIT...",
    "25-01-2021",
    "IE00BGBN6P67",
    "Währungswechsel (Ausbuchung)",
    "CHF",
    "-1'474.06",
    "CHF",
    "210.79",
    "25-01-2021",
    "16:15",
    "INVESCO ELWOOD GLOBAL BLOCKCHAIN",
    "UCIT...",
    "25-01-2021",
    "IE00BGBN6P67",
    "Transaktionsgebühr",
    "CHF",
    "-0.44",
    "CHF",
    "1'684.85",
    "25-01-2021",
    "16:15",
    "INVESCO ELWOOD GLOBAL BLOCKCHAIN",
    "UCIT...",
    "25-01-2021",
    "IE00BGBN6P67",
    "Transaktionsgebühr",
    "CHF",
    "-2.16",
    "CHF",
    "1'685.29",
    "25-01-2021",
    "16:15",
    "INVESCO ELWOOD GLOBAL BLOCKCHAIN",
    "UCIT...",
    "25-01-2021",
    "IE00BGBN6P67",
    "Kauf 17 zu je 80.4 EUR (IE00BGBN6P67)",
    "EUR",
    "-1'366.80",
    "EUR",
    "-1'366.80",
    "25-01-2021",
    "16:04",
    "25-01-2021",
    "SOFORT Zahlungsgebühr",
    "CHF",
    "-1.25",
    "CHF",
    "1'687.45",
    "25-01-2021",
    "16:04",
    "25-01-2021",
    "SOFORT Einzahlung",
    "CHF",
    "1'400.00",
    "CHF",
    "1'688.70",
    "21-01-2021",
    "00:00",
    "FUNDSHARE UCITS CHF CASH FUND",
    "20-01-2021",
    "NL0011280581",
    "Geldmarktfonds Preisänderung (CHF)",
    "CHF",
    "-0.03",
    "CHF",
    "288.70",
    "19-01-2021",
    "12:03",
    "FUNDSHARE UCITS CHF CASH FUND",
    "18-01-2021",
    "NL0011280581",
    "Geldmarktfonds Umwandlung: Verkauf 0.0842 zu je 0.9765",
    "CHF",
    "CHF",
    "288.73",
    "15-01-2021",
    "12:03",
    "FUNDSHARE UCITS CHF CASH FUND",
    "14-01-2021",
    "NL0011280581",
    "Geldmarktfonds Umwandlung: Verkauf 822.0662 zu je",
    "0.9765 CHF",
    "CHF",
    "288.73",
    "14-01-2021",
    "08:20",
    "13-01-2021",
    "Währungswechsel (Ausbuchung)",
    "CHF",
    "-802.83",
    "CHF",
    "288.73",
    "14-01-2021",
    "08:20",
    "13-01-2021",
    "Währungswechsel (Ausbuchung)",
    "EUR",
    "743.16",
    "EUR",
    "0.00",
    "0.9257",
    "14-01-2021",
    "00:00",
    "FUNDSHARE UCITS CHF CASH FUND",
    "13-01-2021",
    "NL0011280581",
    "Geldmarktfonds Preisänderung (CHF)",
    "CHF",
    "-0.11",
    "CHF",
    "1'091.56",
    "13-01-2021",
    "12:02",
    "FUNDSHARE UCITS CHF CASH FUND",
    "12-01-2021",
    "NL0011280581",
    "Geldmarktfonds Umwandlung: Kauf 1'022.6806 zu je 0.9766",
    "CHF",
    "CHF",
    "1'091.67",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "edzsjezlvjjob@ebnnuh.kd",
    "I",
    "www.degiro.ch",
    "Seite 1 /",
    "3",
    "Konto 2021-01-26"
  ],
  [
    "Fnrs Itfek Jsbi",
    "Hmgickxybcpgeiyvvj 02",
    "7394 Tüahvb",
    "Kscyijxnxyu",
    "Fnkfyjgvnoea:",
    "******stk",
    "(084347597)",
    "Datum",
    "Uhrze",
    "Produkt",
    "Valutadatum",
    "ISIN",
    "Beschreibung",
    "Änderung",
    "Saldo",
    "FX",
    "13-01-2021",
    "08:12",
    "CORE ONE LABS INC.",
    "13-01-2021",
    "CA21872J2083",
    "Transaktionsgebühr",
    "EUR",
    "-0.66",
    "EUR",
    "-743.16",
    "13-01-2021",
    "08:12",
    "CORE ONE LABS INC.",
    "13-01-2021",
    "CA21872J2083",
    "Transaktionsgebühr",
    "EUR",
    "-7.50",
    "EUR",
    "-742.50",
    "13-01-2021",
    "08:12",
    "CORE ONE LABS INC.",
    "13-01-2021",
    "CA21872J2083",
    "Kauf 1'000 zu je 0.735 EUR (CA21872J2083)",
    "EUR",
    "-735.00",
    "EUR",
    "-735.00",
    "12-01-2021",
    "22:29",
    "12-01-2021",
    "SOFORT Zahlungsgebühr",
    "CHF",
    "-1.25",
    "CHF",
    "1'091.67",
    "12-01-2021",
    "22:29",
    "12-01-2021",
    "SOFORT Einzahlung",
    "CHF",
    "1'000.00",
    "CHF",
    "1'092.92",
    "11-01-2021",
    "00:00",
    "FUNDSHARE UCITS CHF CASH FUND",
    "10-01-2021",
    "NL0011280581",
    "Geldmarktfonds Preisänderung (CHF)",
    "CHF",
    "-0.02",
    "CHF",
    "92.92",
    "06-01-2021",
    "12:03",
    "FUNDSHARE UCITS CHF CASH FUND",
    "05-01-2021",
    "NL0011280581",
    "Geldmarktfonds Umwandlung: Verkauf 5.0152 zu je 0.977",
    "CHF",
    "CHF",
    "92.94",
    "06-01-2021",
    "00:00",
    "FUNDSHARE UCITS CHF CASH FUND",
    "05-01-2021",
    "NL0011280581",
    "Geldmarktfonds Preisänderung (CHF)",
    "CHF",
    "-0.02",
    "CHF",
    "92.94",
    "05-01-2021",
    "07:58",
    "04-01-2021",
    "Währungswechsel (Ausbuchung)",
    "CHF",
    "-4.90",
    "CHF",
    "92.96",
    "05-01-2021",
    "07:58",
    "04-01-2021",
    "Währungswechsel (Ausbuchung)",
    "EUR",
    "4.54",
    "EUR",
    "0.00",
    "0.9254",
    "04-01-2021",
    "11:09",
    "31-12-2020",
    "Einrichtung von Handelsmodalitäten 2020 (New York Stock",
    "Exchange - NSY)",
    "EUR",
    "-2.27",
    "EUR",
    "-4.54",
    "04-01-2021",
    "11:09",
    "31-12-2020",
    "Einrichtung von Handelsmodalitäten 2020 (Xetra - XET)",
    "EUR",
    "-2.27",
    "EUR",
    "-2.27",
    "30-12-2020",
    "00:00",
    "FUNDSHARE UCITS CHF CASH FUND",
    "29-12-2020",
    "NL0011280581",
    "Geldmarktfonds Preisänderung (CHF)",
    "CHF",
    "-0.01",
    "CHF",
    "97.86",
    "29-12-2020",
    "00:00",
    "FUNDSHARE UCITS CHF CASH FUND",
    "28-12-2020",
    "NL0011280581",
    "Geldmarktfonds Preisänderung (CHF)",
    "CHF",
    "-0.01",
    "CHF",
    "97.87",
    "28-12-2020",
    "00:00",
    "FUNDSHARE UCITS CHF CASH FUND",
    "27-12-2020",
    "NL0011280581",
    "Geldmarktfonds Preisänderung (CHF)",
    "CHF",
    "-0.01",
    "CHF",
    "97.88",
    "24-12-2020",
    "13:13",
    "FUNDSHARE UCITS CHF CASH FUND",
    "23-12-2020",
    "NL0011280581",
    "Geldmarktfonds Umwandlung: Kauf 99.959 zu je 0.9774 CHF",
    "CHF",
    "-0.01",
    "CHF",
    "97.89",
    "24-12-2020",
    "00:00",
    "FUNDSHARE UCITS CHF CASH FUND",
    "23-12-2020",
    "NL0011280581",
    "Geldmarktfonds Preisänderung (CHF)",
    "CHF",
    "-0.00",
    "CHF",
    "97.90",
    "23-12-2020",
    "15:30",
    "FEDEX CORPORATION COMM",
    "23-12-2020",
    "US31428X1063",
    "Währungswechsel (Einbuchung)",
    "USD",
    "547.28",
    "USD",
    "0.00",
    "1.1225",
    "23-12-2020",
    "15:30",
    "FEDEX CORPORATION COMM",
    "23-12-2020",
    "US31428X1063",
    "Währungswechsel (Ausbuchung)",
    "CHF",
    "-487.54",
    "CHF",
    "97.90",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "ruoafxfqugnbw@cmojsz.ih",
    "I",
    "www.degiro.ch",
    "Seite 2 /",
    "3",
    "Konto 2021-01-26"
  ],
  [
    "Nefc Wkkaa Pske",
    "Kimknocuxatzkvklvh 27",
    "0133 Uüwsmc",
    "Kirsfxdoqrr",
    "Qqgflvvjnrxg:",
    "******bpk",
    "(262081751)",
    "Datum",
    "Uhrze",
    "Produkt",
    "Valutadatum",
    "ISIN",
    "Beschreibung",
    "Änderung",
    "Saldo",
    "FX",
    "23-12-2020",
    "15:30",
    "FEDEX CORPORATION COMM",
    "23-12-2020",
    "US31428X1063",
    "Kauf 2 zu je 273.64 USD (US31428X1063)",
    "USD",
    "-547.28",
    "USD",
    "-547.28",
    "23-12-2020",
    "12:37",
    "CARRIER GLOBAL CORP.",
    "23-12-2020",
    "US14448C1045",
    "Währungswechsel (Einbuchung)",
    "EUR",
    "376.80",
    "EUR",
    "0.00",
    "0.9213",
    "23-12-2020",
    "12:37",
    "CARRIER GLOBAL CORP.",
    "23-12-2020",
    "US14448C1045",
    "Währungswechsel (Ausbuchung)",
    "CHF",
    "-408.97",
    "CHF",
    "585.44",
    "23-12-2020",
    "12:37",
    "CARRIER GLOBAL CORP.",
    "23-12-2020",
    "US14448C1045",
    "Transaktionsgebühr",
    "CHF",
    "-0.20",
    "CHF",
    "994.41",
    "23-12-2020",
    "12:37",
    "CARRIER GLOBAL CORP.",
    "23-12-2020",
    "US14448C1045",
    "Transaktionsgebühr",
    "CHF",
    "-4.34",
    "CHF",
    "994.61",
    "23-12-2020",
    "12:37",
    "CARRIER GLOBAL CORP.",
    "23-12-2020",
    "US14448C1045",
    "Kauf 12 zu je 31.4 EUR (US14448C1045)",
    "EUR",
    "-376.80",
    "EUR",
    "-376.80",
    "23-12-2020",
    "12:02",
    "23-12-2020",
    "SOFORT Zahlungsgebühr",
    "CHF",
    "-1.25",
    "CHF",
    "998.95",
    "23-12-2020",
    "12:02",
    "23-12-2020",
    "SOFORT Einzahlung",
    "CHF",
    "1'000.00",
    "CHF",
    "1'000.20",
    "22-12-2020",
    "12:03",
    "FUNDSHARE UCITS CHF CASH FUND",
    "21-12-2020",
    "NL0011280581",
    "Geldmarktfonds Umwandlung: Kauf 0.2046 zu je 0.9774 CHF",
    "CHF",
    "0.20",
    "19-12-2020",
    "12:54",
    "19-12-2020",
    "SOFORT Einzahlung",
    "CHF",
    "0.20",
    "CHF",
    "0.20",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "djwgottwwtmuv@rnhsst.zo",
    "I",
    "www.degiro.ch",
    "Seite 3 /",
    "3",
    "Konto 2021-01-26"
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #1303: [DEGIRO] iMPORT dEGIRO
der Import der angehängte dEGIRO Datei funktioniert nicht.

Bitte um Mitteilung warum nicht ?

## Document
<details><summary>Transactions(27).pdf</summary><p>

```json
[
  [
    "Xxxx XXXXXX XXXXX Xxxxxx",
    "Pagenstr. 66",
    "59494 Soest",
    "Germany",
    "Benutzername:",
    "*****let",
    "(31001159)",
    "Transaktionsübersicht von 26-01-2021 bis 27-01-2021",
    "Datum",
    "Uhrzei",
    "t",
    "Produkt",
    "ISIN",
    "Referen",
    "zbörse",
    "Ausführungso",
    "rt",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährung",
    "Wert",
    "Wechse",
    "lkurs",
    "Transaktions",
    "kosten",
    "Gesamt",
    "26-01-2021",
    "21:52",
    "AMERICAN WELL",
    "CORPORATION CLASS A",
    "COMMON STOCK",
    "US03044L1052",
    "NSY",
    "XNAS",
    "-20",
    "38,00",
    "USD",
    "760,00",
    "USD",
    "623,44",
    "EUR",
    "1,2178",
    "-0,57",
    "EUR",
    "622,87",
    "EUR",
    "26-01-2021",
    "17:50",
    "DATADOG INC - CLASS A",
    "US23804L1035",
    "NDQ",
    "CDED",
    "5",
    "104,86",
    "USD",
    "-524,30",
    "USD",
    "-431,27",
    "EUR",
    "1,2145",
    "-0,52",
    "EUR",
    "-431,79",
    "EUR",
    "26-01-2021",
    "17:46",
    "AMERICAN WELL",
    "CORPORATION CLASS A",
    "COMMON STOCK",
    "US03044L1052",
    "NSY",
    "XNAS",
    "-30",
    "36,10",
    "USD",
    "1.083,00",
    "USD",
    "888,92",
    "EUR",
    "1,2171",
    "-0,60",
    "EUR",
    "888,32",
    "EUR",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "xxxxxxxxxxxxx@xxxxxx.xx",
    "I",
    "www.degiro.de",
    "Seite 1 /",
    "1",
    "Konto 2021-01-27"
  ]
]

```

</p></details>

## Community profile

https://community.tresor.one/u/ab166064

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #1319: [degiro] ganzes pdf wird nicht importiert
Dividenden ließen sich aus dem Degio Kontoauszug leider nicht importieren, schade. So macht das ganze nicht viel nutzen. 
Außerdem werden irgendwelche voreingestellten Gebühren berechnet/angezeigt die gar nicht stimmen und bearbeiten geht auch nicht. Also bevor ich hier monatliche Gebühren bezahle, brauche ich das gescheit funktionsfähig und einfach. Außerdem sind 3 Depots zu wenig. Habe einiges zu verwalten. 
MfG
Martin [Redacted by DHo]

## Document
<details><summary>Transactions (4).pdf</summary><p>

```json
[
  [
    "123",
    "123",
    "123",
    "123",
    "123",
    "123",
    "123",
    "Transaktionsübersicht von 21-01-2021 bis 27-01-2021",
    "Datum",
    "Uhrzei",
    "t",
    "Produkt",
    "ISIN",
    "Referen",
    "zbörse",
    "Ausführungso",
    "rt",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährung",
    "Wert",
    "Wechse",
    "lkurs",
    "Transaktions",
    "kosten",
    "Gesamt",
    "27-01-2021",
    "21:57",
    "TWITTER INC. COMMON S",
    "US90184L1026",
    "NSY",
    "XNYS",
    "30",
    "48,30",
    "USD",
    "-1.449,00",
    "USD",
    "-1.197,22",
    "EUR",
    "1,2091",
    "-0,60",
    "EUR",
    "-1.197,82",
    "EUR",
    "27-01-2021",
    "21:36",
    "CBOE GLOBAL MARKETS INC",
    "US12503M1080",
    "NSY",
    "XNAS",
    "20",
    "92,26",
    "USD",
    "-1.845,20",
    "USD",
    "-1.524,96",
    "EUR",
    "1,2088",
    "-0,57",
    "EUR",
    "-1.525,53",
    "EUR",
    "27-01-2021",
    "20:49",
    "MONSTER BEVERAGE",
    "CORPO",
    "US61174X1090",
    "NDQ",
    "CDED",
    "15",
    "86,17",
    "USD",
    "-1.292,55",
    "USD",
    "-1.067,25",
    "EUR",
    "1,2099",
    "-0,55",
    "EUR",
    "-1.067,80",
    "EUR",
    "27-01-2021",
    "15:31",
    "VERTEX PHARMACEUTICALS",
    "US92532F1003",
    "NDQ",
    "XNAS",
    "7",
    "230,00",
    "USD",
    "-1.610,00",
    "USD",
    "-1.330,91",
    "EUR",
    "1,2085",
    "-0,02",
    "EUR",
    "-1.330,93",
    "EUR",
    "27-01-2021",
    "15:31",
    "VERTEX PHARMACEUTICALS",
    "US92532F1003",
    "NDQ",
    "XNAS",
    "3",
    "230,00",
    "USD",
    "-690,00",
    "USD",
    "-570,20",
    "EUR",
    "1,2089",
    "-0,51",
    "EUR",
    "-570,71",
    "EUR",
    "27-01-2021",
    "15:30",
    "SHOPIFY INC. CLASS A S",
    "CA82509L1076",
    "NSY",
    "XNYS",
    "1",
    "1.149,92",
    "USD",
    "-1.149,92",
    "USD",
    "-949,88",
    "EUR",
    "1,2094",
    "-0,50",
    "EUR",
    "-950,38",
    "EUR",
    "26-01-2021",
    "18:58",
    "CENTENE CORPORATION CO",
    "US15135B1017",
    "NSY",
    "XNYS",
    "70",
    "60,50",
    "USD",
    "-4.235,00",
    "USD",
    "-3.483,59",
    "EUR",
    "1,2145",
    "-0,73",
    "EUR",
    "-3.484,32",
    "EUR",
    "26-01-2021",
    "16:38",
    "ANTHEM INC. COMMON ST",
    "US0367521038",
    "NSY",
    "XNYS",
    "10",
    "312,60",
    "USD",
    "-3.126,00",
    "USD",
    "-2.568,19",
    "EUR",
    "1,216",
    "-0,53",
    "EUR",
    "-2.568,72",
    "EUR",
    "25-01-2021",
    "21:57",
    "AMGEN INC. - COMMON ST",
    "US0311621009",
    "NDQ",
    "XNAS",
    "-18",
    "257,00",
    "USD",
    "4.626,00",
    "USD",
    "3.802,62",
    "EUR",
    "1,2153",
    "-0,56",
    "EUR",
    "3.802,06",
    "EUR",
    "25-01-2021",
    "20:17",
    "MONSTER BEVERAGE",
    "CORPO",
    "US61174X1090",
    "NDQ",
    "ARCX",
    "15",
    "88,30",
    "USD",
    "-1.324,50",
    "USD",
    "-1.090,93",
    "EUR",
    "1,2129",
    "-0,55",
    "EUR",
    "-1.091,48",
    "EUR",
    "25-01-2021",
    "18:16",
    "ANTHEM INC. COMMON ST",
    "US0367521038",
    "NSY",
    "XNAS",
    "15",
    "314,00",
    "USD",
    "-4.710,00",
    "USD",
    "-3.879,10",
    "EUR",
    "1,213",
    "-0,55",
    "EUR",
    "-3.879,65",
    "EUR",
    "25-01-2021",
    "16:06",
    "SQUARE INC - A",
    "US8522341036",
    "NSY",
    "XNYS",
    "5",
    "219,50",
    "USD",
    "-1.097,50",
    "USD",
    "-905,30",
    "EUR",
    "1,2111",
    "-0,52",
    "EUR",
    "-905,82",
    "EUR",
    "22-01-2021",
    "19:48",
    "SKILLZ INC",
    "US83067L1098",
    "NSY",
    "ARCX",
    "45",
    "28,00",
    "USD",
    "-1.260,00",
    "USD",
    "-1.035,59",
    "EUR",
    "1,2155",
    "-0,65",
    "EUR",
    "-1.036,24",
    "EUR",
    "22-01-2021",
    "14:05",
    "LINDE PLC",
    "IE00BZ12WP82",
    "XET",
    "XETA",
    "30",
    "205,40",
    "EUR",
    "-6.162,00",
    "EUR",
    "-6.162,00",
    "EUR",
    "-3,11",
    "EUR",
    "-6.165,11",
    "EUR",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "xxxxxxxxxxxxx@xxxxxx.xx",
    "I",
    "www.degiro.de",
    "Seite 1 /",
    "1",
    "Konto 2021-01-27"
  ]
]

```

</p></details>

## Community profile

ich weiß leider nicht welchen link ich da setzen soll. email ist [redacted by DHo]
---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #1321: [DeGiro] Es können keine Umsätze eingfügt werden
## Document
<details><summary>Transactions-33.pdf</summary><p>

```json
[
  [
    "Xxxx Xxxx-Xxxxxx Xxxxxxxx",
    "Xöxxxxxxxxxx Xxx. 0",
    "00000 Xxxxxxx",
    "Xxxxxxx",
    "Benutzername:",
    "***xXx",
    "(00000000)",
    "Transaktionsübersicht von 25-01-2021 bis 27-01-2021",
    "Datum",
    "Uhrzei",
    "t",
    "Produkt",
    "ISIN",
    "Referen",
    "zbörse",
    "Ausführungso",
    "rt",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährung",
    "Wert",
    "Wechse",
    "lkurs",
    "Transaktions",
    "kosten",
    "Gesamt",
    "26-01-2021",
    "21:43",
    "PLUG POWER INC. - COM",
    "US72919P2020",
    "NDQ",
    "SOHO",
    "-1",
    "73,15",
    "USD",
    "73,15",
    "USD",
    "60,01",
    "EUR",
    "1,2178",
    "-0,50",
    "EUR",
    "59,51",
    "EUR",
    "26-01-2021",
    "16:46",
    "SPORTSMAN'S WAREHOUSE",
    "US84920Y1064",
    "NDQ",
    "CDED",
    "-5",
    "17,58",
    "USD",
    "87,90",
    "USD",
    "72,08",
    "EUR",
    "1,2183",
    "-0,52",
    "EUR",
    "71,56",
    "EUR",
    "26-01-2021",
    "16:44",
    "PLUG POWER INC. - COM",
    "US72919P2020",
    "NDQ",
    "CDED",
    "-1",
    "70,77",
    "USD",
    "70,77",
    "USD",
    "58,03",
    "EUR",
    "1,2184",
    "-0,50",
    "EUR",
    "57,53",
    "EUR",
    "25-01-2021",
    "20:01",
    "PEPSICO INC",
    "US7134481081",
    "NDQ",
    "BATS",
    "-1",
    "139,70",
    "USD",
    "139,70",
    "USD",
    "114,83",
    "EUR",
    "1,2154",
    "-0,50",
    "EUR",
    "114,33",
    "EUR",
    "25-01-2021",
    "20:01",
    "APPLE INC. - COMMON ST",
    "US0378331005",
    "NDQ",
    "ARCX",
    "-1",
    "142,66",
    "USD",
    "142,66",
    "USD",
    "117,26",
    "EUR",
    "1,2154",
    "-0,50",
    "EUR",
    "116,76",
    "EUR",
    "25-01-2021",
    "18:01",
    "PLUG POWER INC. - COM",
    "US72919P2020",
    "NDQ",
    "XNAS",
    "-1",
    "66,26",
    "USD",
    "66,26",
    "USD",
    "54,48",
    "EUR",
    "1,2151",
    "-0,50",
    "EUR",
    "53,98",
    "EUR",
    "25-01-2021",
    "17:59",
    "PALANTIR TECHNOLOGIES",
    "INC-A",
    "US69608A1088",
    "NSY",
    "SOHO",
    "-1",
    "35,75",
    "USD",
    "35,75",
    "USD",
    "29,40",
    "EUR",
    "1,2149",
    "-0,50",
    "EUR",
    "28,90",
    "EUR",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "xxxxxxxxxxxxx@xxxxxx.xx",
    "I",
    "www.degiro.de",
    "Seite 1 /",
    "1",
    "Konto 2021-01-27"
  ]
]

```

</p></details>

## Community profile

https://community.tresor.one/u/8877a93f

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #1360: [Degiro] Keine Position von degiro erkannt
## Document
<details><summary>Transactions.pdf</summary><p>

```json
[
  [
    "Xxxx Xxxxxxxxx Xxxxxxxx",
    "Xxxxxxxxxxx Xxxxßx 000",
    "00000 Xxxxxxxxxx",
    "Germany",
    "Benutzername:",
    "********xxx",
    "(00000000)",
    "Transaktionsübersicht von 30-12-2020 bis 29-01-2021",
    "Datum",
    "Uhrzei",
    "t",
    "Produkt",
    "ISIN",
    "Referen",
    "zbörse",
    "Ausführungso",
    "rt",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährung",
    "Wert",
    "Wechse",
    "lkurs",
    "Transaktions",
    "kosten",
    "Gesamt",
    "29-01-2021",
    "15:41",
    "AMC ENTERTAINMENT HOLD",
    "US00165C1045",
    "NSY",
    "XNYS",
    "15",
    "13,00",
    "USD",
    "-195,00",
    "USD",
    "-160,55",
    "EUR",
    "1,2134",
    "-0,55",
    "EUR",
    "-161,10",
    "EUR",
    "29-01-2021",
    "15:30",
    "NOKIA CORPORATION SPON",
    "US6549022043",
    "NSY",
    "XNYS",
    "90",
    "5,12",
    "USD",
    "-460,80",
    "USD",
    "-379,32",
    "EUR",
    "1,2136",
    "-0,80",
    "EUR",
    "-380,12",
    "EUR",
    "29-01-2021",
    "13:52",
    "NESTLE SA",
    "CH0038863350",
    "SWX",
    "MESI",
    "-6",
    "100,80",
    "CHF",
    "604,80",
    "CHF",
    "559,66",
    "EUR",
    "1,0796",
    "-4,28",
    "EUR",
    "555,38",
    "EUR",
    "15-01-2021",
    "09:10",
    "NESTLE SA",
    "CH0038863350",
    "SWX",
    "XSWX",
    "4",
    "100,02",
    "CHF",
    "-400,08",
    "CHF",
    "-371,24",
    "EUR",
    "1,0766",
    "-4,19",
    "EUR",
    "-375,43",
    "EUR",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "xxxxxxxxxxxxx@xxxxxx.xx",
    "I",
    "www.degiro.de",
    "Seite 1 /",
    "1",
    "Konto 2021-01-29"
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

### PR DESCRIPTION
**Pull request by SirGibihm**
Patching a change in the .pdf format of DeGiro due to a reference stock exchange being named which breaks formatting.
* Fixes #1360 
* Added Testcase #1360 
* Fixes #1321 (only validated in local test environment after fixes from #1360)
* Fixes #1319 (only validated in local test environment after fixes from #1360)
* Fixes #1303 (only validated in local test environment after fixes from #1360)
* Fixes #1284 (only validated in local test environment after fixes from #1360)
* Fixes #1276 
* Added Testcase #1276

### CODE REVIEW

File: src/brokers/degiro.js [hunk 1]
```diff
@@ -100,14 +103,19 @@ const parseTransaction = (content, index, numberParser) => {
   if (currency !== baseCurrency) {
     activity.foreignCurrency = currency;
   }
-
+  console.log(activity);
```
Comment (dredav) [inline src/brokers/degiro.js:106]: Did we need this console.log longer?

**Review by dredav — COMMENTED** [review]
Looks good, found only one very small thing...

File: src/brokers/degiro.js (hunk 1 above)
Comment (SirGibihm) [reply src/brokers/degiro.js]: Absolutely not ^^' Removed

**Review by dredav — APPROVED** [review]
