### PR TITLE
[trade republic] Fix parsing of quarter statement Q4/2020

### LINKED ISSUE #1188: Falsches einpflegen der Trade Republic JAHRESDEPOTABSTIMMUNG
Kann gerne einen Report zur Verfügung stellen...

## Document
<details><summary>2020_Q4_JAHRESDEPOTABSTIMMUNG.pdf</summary><p>

```json
[
  [
    "TRADE REPUBLIC BANK GMBH",
    "KASTANIENALLEE 32",
    "10435 BERLIN",
    "Hgqvwh Hzjim",
    "Asasxngrßl 22",
    "94739 Shoclzreh",
    "SEITE",
    "1",
    "von",
    "6",
    "DATUM",
    "12.01.2021",
    "DEPOT",
    "0887640644",
    "Trade Republic Bank GmbH",
    "Kastanienallee 32",
    "10435 Berlin",
    "www.traderepublic.com",
    "zadypbi@urdmkaiwggdjd.nxn",
    "Sitz der Gesellschaft: Düsseldorf",
    "AG Düsseldorf HRB 85864",
    "USt-ID DE307510626",
    "Geschäftsführer",
    "Andreas Willius",
    "Karsten Müller",
    "DAGR",
    "/ f7e7-1a42",
    "JAHRESDEPOTABSTIMMUNG",
    "zum 31.12.2020",
    "POSITIONEN",
    "Aufstellung über die Wertpapiere in Deinem Depot 0887640644 zum 31.12.2020.",
    "Deine Wertpapiere werden in Girosammelverwahrung in Deutschland verwahrt, sofern unten nichts anderes",
    "angegeben ist.",
    "Wir bitten Dich, diese Aufstellung umgehend zu prüfen. Wenn Du Beanstandungen hast, wende Dich bitte",
    "unverzüglich an unseren Kundenservice.",
    "NOMINALE",
    "WERTPAPIERBEZEICHNUNG",
    "KURS PRO STÜCK",
    "KAUFWERT IN EUR",
    "GEWINN / VERLUST",
    "KURSWERT IN EUR",
    "50 Stk.",
    "First Graphene Ltd.",
    "Registered Shares o.N.",
    "ISIN: AU000000FGR3",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Australien",
    "0,15",
    "30.12.2020",
    "4,00",
    "3,26",
    "81,5%",
    "7,26",
    "2.137 Stk.",
    "Ballard Power Systems",
    "Inc.",
    "Registered Shares o.N.",
    "ISIN: CA0585861085",
    "18,10",
    "30.12.2020",
    "30,00",
    "8,68",
    "28,93%",
    "38,68",
    "1000 Stk.",
    "Manganese X Energy",
    "Corp.",
    "Registered Shares o.N.",
    "ISIN: CA5626781028",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Kanada",
    "0,20",
    "30.12.2020",
    "234,80",
    "-39,30",
    "-16,74%",
    "195,50",
    "61.1149",
    "Stk.",
    "Standard Lithium Ltd.",
    "Registered Shares o.N.",
    "ISIN: CA8536061010",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Kanada",
    "1,68",
    "30.12.2020",
    "80,00",
    "22,67",
    "28,34%",
    "102,67",
    "45 Stk.",
    "Ynvisible Interactive Inc.",
    "Registered Shares o.N.",
    "ISIN: CA9858441095",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Kanada",
    "0,50",
    "30.12.2020",
    "16,11",
    "6,26",
    "38,86%",
    "22,37",
    "35 Stk.",
    "BYD Co. Ltd.",
    "Registered Shares H YC 1",
    "ISIN: CNE100000296",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland:",
    "Sonderverwaltungsregion",
    "Hongkong",
    "20,36",
    "30.12.2020",
    "579,05",
    "133,55",
    "23,06%",
    "712,60",
    "1.5792",
    "Stk.",
    "Nordex SE",
    "Inhaber-Aktien o.N.",
    "ISIN: DE000A0D6554",
    "22,32",
    "30.12.2020",
    "30,00",
    "5,25",
    "17,5%",
    "35,25"
  ],
  [
    "SEITE",
    "2",
    "von",
    "6",
    "DATUM",
    "12.01.2021",
    "DEPOT",
    "1651781002",
    "Trade Republic Bank GmbH",
    "Kastanienallee 32",
    "10435 Berlin",
    "www.traderepublic.com",
    "qfwqpat@kaulydwfwyuqn.khl",
    "Sitz der Gesellschaft: Düsseldorf",
    "AG Düsseldorf HRB 85864",
    "USt-ID DE307510626",
    "Geschäftsführer",
    "Andreas Willius",
    "Karsten Müller",
    "DAGR",
    "/ f7e7-1a42",
    "1.332 Stk.",
    "VARTA AG",
    "Inhaber-Aktien o.N.",
    "ISIN: DE000A0TGJ55",
    "118,10",
    "30.12.2020",
    "149,96",
    "7,35",
    "4,9%",
    "157,31",
    "2.2808",
    "Stk.",
    "TeamViewer AG",
    "Inhaber-Aktien o.N.",
    "ISIN: DE000A2YN900",
    "43,85",
    "30.12.2020",
    "91,72",
    "8,29",
    "9,04%",
    "100,01",
    "1.4237",
    "Stk.",
    "Zalando SE",
    "Inhaber-Aktien o.N.",
    "ISIN: DE000ZAL1111",
    "91,08",
    "30.12.2020",
    "119,99",
    "9,68",
    "8,07%",
    "129,67",
    "1 Stk.",
    "Borussia Dortmund",
    "GmbH&Co.KGaA",
    "Inhaber-Aktien o.N.",
    "ISIN: DE0005493092",
    "5,50",
    "30.12.2020",
    "6,06",
    "-0,55",
    "-9,08%",
    "5,51",
    "0.225 Stk.",
    "Volkswagen AG",
    "Vorzugsaktien o.St. o.N.",
    "ISIN: DE0007664039",
    "151,48",
    "30.12.2020",
    "29,98",
    "4,10",
    "13,68%",
    "34,08",
    "12.3676",
    "Stk.",
    "ITM Power PLC",
    "Registered Shares LS -,",
    "05",
    "ISIN: GB00B0130H42",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Vereinigtes",
    "Königreich",
    "5,44",
    "30.12.2020",
    "40,00",
    "27,28",
    "68,2%",
    "67,28",
    "1.2089",
    "Stk.",
    "Unilever PLC",
    "Registered Shares LS -,",
    "031111",
    "ISIN: GB00B10RZP78",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Vereinigtes",
    "Königreich",
    "49,26",
    "30.12.2020",
    "58,99",
    "0,56",
    "0,95%",
    "59,55",
    "30 Stk.",
    "Geely Automobile",
    "Holdings Ltd.",
    "Registered Shares HD -,",
    "02",
    "ISIN: KYG3777B1032",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland:",
    "Sonderverwaltungsregion",
    "Hongkong",
    "2,55",
    "30.12.2020",
    "56,22",
    "20,42",
    "36,32%",
    "76,64",
    "30 Stk.",
    "NEL ASA",
    "Navne-Aksjer NK -,20",
    "ISIN: NO0010081235",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Norwegen",
    "2,69",
    "30.12.2020",
    "56,04",
    "24,66",
    "44%",
    "80,70",
    "15 Stk.",
    "Brill. China Autom. Hldgs",
    "Ltd.",
    "Registered Shares DL-,01",
    "ISIN: BMG1368B1028",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland:",
    "Sonderverwaltungsregion",
    "Hongkong",
    "0,68",
    "30.12.2020",
    "12,68",
    "-2,50",
    "-19,72%",
    "10,18"
  ],
  [
    "SEITE",
    "3",
    "von",
    "6",
    "DATUM",
    "12.01.2021",
    "DEPOT",
    "0134314801",
    "Trade Republic Bank GmbH",
    "Kastanienallee 32",
    "10435 Berlin",
    "www.traderepublic.com",
    "swguczs@tclhrcvzathzc.xoo",
    "Sitz der Gesellschaft: Düsseldorf",
    "AG Düsseldorf HRB 85864",
    "USt-ID DE307510626",
    "Geschäftsführer",
    "Andreas Willius",
    "Karsten Müller",
    "DAGR",
    "/ f7e7-1a42",
    "55 Stk.",
    "Xiaomi Corp.",
    "Registered Shares Cl.B o.",
    "N.",
    "ISIN: KYG9830T1067",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland:",
    "Sonderverwaltungsregion",
    "Hongkong",
    "3,50",
    "30.12.2020",
    "154,85",
    "37,65",
    "24,31%",
    "192,50",
    "2.1007",
    "Stk.",
    "AT & T Inc.",
    "Registered Shares DL 1",
    "ISIN: US00206R1023",
    "23,27",
    "30.12.2020",
    "50,00",
    "-1,12",
    "-2,24%",
    "48,88",
    "0.422 Stk.",
    "Advanced Micro Devices",
    "Inc.",
    "Registered Shares DL -,",
    "01",
    "ISIN: US0079031078",
    "73,98",
    "30.12.2020",
    "30,00",
    "1,22",
    "4,07%",
    "31,22",
    "0.844 Stk.",
    "Alibaba Group Holding",
    "Ltd.",
    "Reg.Shs (sp.ADRs)/8 DL-,",
    "000025",
    "ISIN: US01609W1027",
    "198,00",
    "30.12.2020",
    "184,93",
    "-17,82",
    "-9,64%",
    "167,11",
    "0.0835",
    "Stk.",
    "Alphabet Inc.",
    "Reg. Shs Cl. A DL-,001",
    "ISIN: US02079K3059",
    "1.436,40",
    "30.12.2020",
    "119,79",
    "0,15",
    "0,13%",
    "119,94",
    "0.0379",
    "Stk.",
    "Amazon.com Inc.",
    "Registered Shares DL -,",
    "01",
    "ISIN: US0231351067",
    "2.718,50",
    "30.12.2020",
    "99,45",
    "3,58",
    "3,6%",
    "103,03",
    "0.3209",
    "Stk.",
    "American States Water",
    "Co.",
    "Registered Shares DL",
    "2,50",
    "ISIN: US0298991011",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Vereinigte",
    "Staaten",
    "63,58",
    "30.12.2020",
    "20,00",
    "0,40",
    "2%",
    "20,40",
    "0.6021",
    "Stk.",
    "Apple Inc.",
    "Registered Shares o.N.",
    "ISIN: US0378331005",
    "110,36",
    "30.12.2020",
    "59,99",
    "6,46",
    "10,77%",
    "66,45",
    "0.6012",
    "Stk.",
    "Cisco Systems Inc.",
    "Registered Shares DL-,",
    "001",
    "ISIN: US17275R1023",
    "36,49",
    "30.12.2020",
    "20,00",
    "1,94",
    "9,7%",
    "21,94",
    "1.0536",
    "Stk.",
    "Coca-Cola Co., The",
    "Registered Shares DL -,",
    "25",
    "ISIN: US1912161007",
    "44,36",
    "30.12.2020",
    "45,00",
    "1,74",
    "3,87%",
    "46,74",
    "0.1034",
    "Stk.",
    "Danaher Corp.",
    "Registered Shares DL -,",
    "01",
    "ISIN: US2358511028",
    "181,50",
    "30.12.2020",
    "19,98",
    "-1,21",
    "-6,06%",
    "18,77"
  ],
  [
    "SEITE",
    "4",
    "von",
    "6",
    "DATUM",
    "12.01.2021",
    "DEPOT",
    "0134314801",
    "Trade Republic Bank GmbH",
    "Kastanienallee 32",
    "10435 Berlin",
    "www.traderepublic.com",
    "msvcshi@bnxlyzlrsvbvz.khk",
    "Sitz der Gesellschaft: Düsseldorf",
    "AG Düsseldorf HRB 85864",
    "USt-ID DE307510626",
    "Geschäftsführer",
    "Andreas Willius",
    "Karsten Müller",
    "DAGR",
    "/ f7e7-1a42",
    "0.7006",
    "Stk.",
    "eBay Inc.",
    "Registered Shares DL -,",
    "001",
    "ISIN: US2786421030",
    "41,55",
    "30.12.2020",
    "30,00",
    "-0,89",
    "-2,97%",
    "29,11",
    "0.7179",
    "Stk.",
    "Intel Corp.",
    "Registered Shares DL -,",
    "001",
    "ISIN: US4581401001",
    "39,96",
    "30.12.2020",
    "30,00",
    "-1,31",
    "-4,37%",
    "28,69",
    "4.4414",
    "Stk.",
    "Iron Mountain Inc.",
    "Registered Shares DL -,",
    "01",
    "ISIN: US46284V1017",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Vereinigte",
    "Staaten",
    "25,00",
    "30.12.2020",
    "100,00",
    "11,04",
    "11,04%",
    "111,04",
    "0.4268",
    "Stk.",
    "JD.com Inc.",
    "R.Shs Cl.A(Sp.ADRs)",
    "/1DL-,00002",
    "ISIN: US47215P1066",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Vereinigte",
    "Staaten",
    "71,00",
    "30.12.2020",
    "29,99",
    "0,31",
    "1,03%",
    "30,30",
    "2.6784",
    "Stk.",
    "JinkoSolar Holding Co.",
    "Ltd.",
    "Reg.Shs (Sp. ADRs)/4 DL-",
    ",00002",
    "ISIN: US47759T1007",
    "55,60",
    "30.12.2020",
    "140,00",
    "8,92",
    "6,37%",
    "148,92",
    "0.3277",
    "Stk.",
    "Johnson & Johnson",
    "Registered Shares DL 1",
    "ISIN: US4781601046",
    "126,40",
    "30.12.2020",
    "39,98",
    "1,44",
    "3,6%",
    "41,42",
    "1.123 Stk.",
    "Kraft Heinz Co., The",
    "Registered Shares DL -,",
    "01",
    "ISIN: US5007541064",
    "28,56",
    "30.12.2020",
    "30,00",
    "2,08",
    "6,93%",
    "32,08",
    "0.1095",
    "Stk.",
    "Mastercard Inc.",
    "Registered Shares A DL -,",
    "0001",
    "ISIN: US57636Q1040",
    "283,85",
    "30.12.2020",
    "29,97",
    "1,11",
    "3,7%",
    "31,08",
    "0.1615",
    "Stk.",
    "McDonald's Corp.",
    "Registered Shares DL-,01",
    "ISIN: US5801351017",
    "174,00",
    "30.12.2020",
    "29,97",
    "-1,87",
    "-6,24%",
    "28,10",
    "0.1693",
    "Stk.",
    "Microsoft Corp.",
    "Registered Shares DL-,",
    "00000625",
    "ISIN: US5949181045",
    "182,86",
    "30.12.2020",
    "29,99",
    "0,97",
    "3,23%",
    "30,96",
    "0.0689",
    "Stk.",
    "NVIDIA Corp.",
    "Registered Shares DL-,",
    "001",
    "ISIN: US67066G1040",
    "423,45",
    "30.12.2020",
    "30,92",
    "-1,74",
    "-5,63%",
    "29,18",
    "0.1781",
    "Stk.",
    "PayPal Holdings Inc.",
    "Reg. Shares DL -,0001",
    "ISIN: US70450Y1038",
    "189,96",
    "30.12.2020",
    "29,98",
    "3,85",
    "12,84%",
    "33,83"
  ],
  [
    "SEITE",
    "5",
    "von",
    "6",
    "DATUM",
    "12.01.2021",
    "DEPOT",
    "0134314801",
    "Trade Republic Bank GmbH",
    "Kastanienallee 32",
    "10435 Berlin",
    "www.traderepublic.com",
    "zmknekv@ntxsvfhvypkjo.flo",
    "Sitz der Gesellschaft: Düsseldorf",
    "AG Düsseldorf HRB 85864",
    "USt-ID DE307510626",
    "Geschäftsführer",
    "Andreas Willius",
    "Karsten Müller",
    "DAGR",
    "/ f7e7-1a42",
    "0.38 Stk.",
    "PepsiCo Inc.",
    "Registered Shares DL -,",
    "0166",
    "ISIN: US7134481081",
    "120,74",
    "30.12.2020",
    "44,98",
    "0,90",
    "2%",
    "45,88",
    "2.4218",
    "Stk.",
    "Plug Power Inc.",
    "Registered Shares DL -,",
    "01",
    "ISIN: US72919P2020",
    "26,75",
    "30.12.2020",
    "40,00",
    "24,78",
    "61,95%",
    "64,78",
    "0.6391",
    "Stk.",
    "Procter & Gamble Co.,",
    "The",
    "Registered Shares o.N.",
    "ISIN: US7427181091",
    "113,02",
    "30.12.2020",
    "74,99",
    "-2,76",
    "-3,68%",
    "72,23",
    "1.9893",
    "Stk.",
    "Realty Income Corp.",
    "Registered Shares DL 1",
    "ISIN: US7561091049",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Vereinigte",
    "Staaten",
    "50,01",
    "30.12.2020",
    "101,43",
    "-1,95",
    "-1,92%",
    "99,48",
    "0.7785",
    "Stk.",
    "Square Inc.",
    "Registered Shs Class A",
    "ISIN: US8522341036",
    "175,78",
    "30.12.2020",
    "129,98",
    "6,86",
    "5,28%",
    "136,84",
    "0.2566",
    "Stk.",
    "Starbucks Corp.",
    "Reg. Shares DL -,001",
    "ISIN: US8552441094",
    "86,24",
    "30.12.2020",
    "19,99",
    "2,14",
    "10,71%",
    "22,13",
    "0.0773",
    "Stk.",
    "Tesla Inc.",
    "Registered Shares DL-,",
    "001",
    "ISIN: US88160R1014",
    "547,80",
    "30.12.2020",
    "29,92",
    "12,42",
    "41,51%",
    "42,34",
    "0.2103",
    "Stk.",
    "3M Co.",
    "Registered Shares DL -,",
    "01",
    "ISIN: US88579Y1010",
    "142,18",
    "30.12.2020",
    "29,99",
    "-0,09",
    "-0,3%",
    "29,90",
    "0.1207",
    "Stk.",
    "VISA Inc.",
    "Reg. Shares Class A DL -,",
    "0001",
    "ISIN: US92826C8394",
    "174,78",
    "30.12.2020",
    "19,98",
    "1,12",
    "5,61%",
    "21,10",
    "0.4165",
    "Stk.",
    "Walmart Inc.",
    "Registered Shares DL -,",
    "10",
    "ISIN: US9311421039",
    "117,94",
    "30.12.2020",
    "49,99",
    "-0,87",
    "-1,74%",
    "49,12",
    "0.1049",
    "Stk.",
    "Waste Management Inc.",
    "(Del.)",
    "Registered Shares DL -,",
    "01",
    "ISIN: US94106L1098",
    "94,86",
    "30.12.2020",
    "10,00",
    "-0,05",
    "-0,5%",
    "9,95",
    "55 Stk.",
    "iShs Core MSCI EM IMI U.",
    "ETF",
    "Registered Shares o.N.",
    "ISIN: IE00BKM4GZ66",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Vereinigtes",
    "Königreich",
    "29,08",
    "30.12.2020",
    "1.459,98",
    "139,53",
    "9,56%",
    "1.599,51"
  ],
  [
    "SEITE",
    "6",
    "von",
    "6",
    "DATUM",
    "12.01.2021",
    "DEPOT",
    "0134314801",
    "Trade Republic Bank GmbH",
    "Kastanienallee 32",
    "10435 Berlin",
    "www.traderepublic.com",
    "bxnfsgs@eynjkykmfrbfs.ilz",
    "Sitz der Gesellschaft: Düsseldorf",
    "AG Düsseldorf HRB 85864",
    "USt-ID DE307510626",
    "Geschäftsführer",
    "Andreas Willius",
    "Karsten Müller",
    "DAGR",
    "/ f7e7-1a42",
    "1.8423",
    "Stk.",
    "iShs Core MSCI EM IMI U.",
    "ETF",
    "Registered Shares o.N.",
    "ISIN: IE00BKM4GZ66",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Irland",
    "29,08",
    "30.12.2020",
    "48,90",
    "4,68",
    "9,57%",
    "53,58",
    "154.8484",
    "Stk.",
    "iShsII-Gl.Clean Energy U.",
    "ETF",
    "Registered Shares o.N.",
    "ISIN: IE00B1XNHC34",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Irland",
    "13,10",
    "30.12.2020",
    "1.668,80",
    "359,09",
    "21,52%",
    "2.027,89",
    "58.1848",
    "Stk.",
    "iShsIII-Core MSCI World",
    "U.ETF",
    "Registered Shs USD",
    "(Acc) o.N.",
    "ISIN: IE00B4L5Y983",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Irland",
    "59,74",
    "30.12.2020",
    "3.200,00",
    "275,84",
    "8,62%",
    "3.475,84",
    "6 Stk.",
    "HSBC Trinkaus &",
    "Burkhardt AG",
    "TurboC O.End BYD",
    "ISIN: DE000TT33KU3",
    "3,12",
    "30.12.2020",
    "17,04",
    "1,68",
    "9,86%",
    "18,72",
    "ANZAHL POSITIONEN: 56",
    "SUMME KURSWERTE: 11016.24 EUR",
    "Bitte beachte:",
    "Soweit Kursangaben fehlen, handelt es sich entweder um Wertpapiere, für die ein Kurs nicht oder nicht",
    "rechtzeitig festgestellt werden konnte oder um nicht notierte Wertpapiere. Eine Gewähr für die Richtigkeit der",
    "Kurse können wir nicht übernehmen. In der Gewinn / Verlust-Rechnung sind steuerliche Aspekte nicht",
    "berücksichtigt.",
    "Bruchstücke aus ETF-Sparplänen werden in Wertpapierrechnung in Deutschland verwahrt."
  ]
]

```

</p></details>

## Community profile

https://community.tresor.one/u/44bcca61

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #1343: [TradeRepublic] Kann nicht importiert werden
## Document
<details><summary>Depotauszug (7).pdf</summary><p>

```json
[
  [
    "TRADE REPUBLIC BANK GMBH",
    "KASTANIENALLEE 32",
    "10435 BERLIN",
    "Xxxxxxx Xxx Xxxxxxxx",
    "Xxxxxxxxxx. 00",
    "00000 Xxxxxxxxx Xxxxxxx",
    "SEITE",
    "1",
    "von",
    "2",
    "DATUM",
    "13.01.2021",
    "DEPOT",
    "0150097401",
    "Trade Republic Bank GmbH",
    "Kastanienallee 32",
    "10435 Berlin",
    "www.traderepublic.com",
    "xxxxxxx@xxxxxxxxxxxxx.xxx",
    "Sitz der Gesellschaft: Düsseldorf",
    "AG Düsseldorf HRB 85864",
    "USt-ID DE307510626",
    "Geschäftsführer",
    "Andreas Willius",
    "Karsten Müller",
    "DAGR",
    "/ b495-9c23",
    "JAHRESDEPOTABSTIMMUNG",
    "zum 31.12.2020",
    "POSITIONEN",
    "Aufstellung über die Wertpapiere in Deinem Depot 0150097401 zum 31.12.2020.",
    "Deine Wertpapiere werden in Girosammelverwahrung in Deutschland verwahrt, sofern unten nichts anderes",
    "angegeben ist.",
    "Wir bitten Dich, diese Aufstellung umgehend zu prüfen. Wenn Du Beanstandungen hast, wende Dich bitte",
    "unverzüglich an unseren Kundenservice.",
    "NOMINALE",
    "WERTPAPIERBEZEICHNUNG",
    "KURS PRO STÜCK",
    "KAUFWERT IN EUR",
    "GEWINN / VERLUST",
    "KURSWERT IN EUR",
    "1 Stk.",
    "Amazon.com Inc.",
    "Registered Shares DL -,",
    "01",
    "ISIN: US0231351067",
    "2.718,50",
    "30.12.2020",
    "2.669,50",
    "49,00",
    "1,84%",
    "2.718,50",
    "3 Stk.",
    "Apple Inc.",
    "Registered Shares o.N.",
    "ISIN: US0378331005",
    "110,36",
    "30.12.2020",
    "289,17",
    "41,91",
    "14,49%",
    "331,08",
    "1 Stk.",
    "Facebook Inc.",
    "Reg.Shares Cl.A DL-,",
    "000006",
    "ISIN: US30303M1027",
    "225,80",
    "30.12.2020",
    "230,25",
    "-4,45",
    "-1,93%",
    "225,80",
    "2 Stk.",
    "Microsoft Corp.",
    "Registered Shares DL-,",
    "00000625",
    "ISIN: US5949181045",
    "182,86",
    "30.12.2020",
    "371,88",
    "-6,16",
    "-1,66%",
    "365,72",
    "2 Stk.",
    "VISA Inc.",
    "Reg. Shares Class A DL -",
    ",0001",
    "ISIN: US92826C8394",
    "174,78",
    "30.12.2020",
    "346,60",
    "2,96",
    "0,85%",
    "349,56",
    "486.8132",
    "Stk.",
    "iSh.STOXX Europe 600",
    "U.ETF DE",
    "Inhaber-Anteile",
    "ISIN: DE0002635307",
    "39,76",
    "30.12.2020",
    "17.520,30",
    "1.832,96",
    "10,46%",
    "19.353,26",
    "391.2356",
    "Stk.",
    "iShs Euro Dividend",
    "UCITS ETF",
    "Registered Shares o.N.",
    "ISIN: IE00B0M62S72",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Irland",
    "17,88",
    "30.12.2020",
    "6.158,06",
    "838,01",
    "13,61%",
    "6.996,07",
    "960.8046",
    "Stk.",
    "iShs Core MSCI EM IMI U.",
    "ETF",
    "Registered Shares o.N.",
    "ISIN: IE00BKM4GZ66",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Vereinigtes",
    "Königreich",
    "29,08",
    "30.12.2020",
    "24.231,76",
    "3.710,36",
    "15,31%",
    "27.942,12"
  ],
  [
    "SEITE",
    "2",
    "von",
    "2",
    "DATUM",
    "13.01.2021",
    "DEPOT",
    "0150097401",
    "Trade Republic Bank GmbH",
    "Kastanienallee 32",
    "10435 Berlin",
    "www.traderepublic.com",
    "xxxxxxx@xxxxxxxxxxxxx.xxx",
    "Sitz der Gesellschaft: Düsseldorf",
    "AG Düsseldorf HRB 85864",
    "USt-ID DE307510626",
    "Geschäftsführer",
    "Andreas Willius",
    "Karsten Müller",
    "DAGR",
    "/ b495-9c23",
    "205.2358",
    "Stk.",
    "iShs Core MSCI EM IMI U.",
    "ETF",
    "Registered Shares o.N.",
    "ISIN: IE00BKM4GZ66",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Irland",
    "29,08",
    "30.12.2020",
    "5.176,10",
    "792,57",
    "15,31%",
    "5.968,67",
    "82.4028",
    "Stk.",
    "iShsII-Global Water",
    "UCITS ETF",
    "Registered Shares o.N.",
    "ISIN: IE00B1TXK627",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Irland",
    "45,28",
    "30.12.2020",
    "3.460,00",
    "271,61",
    "7,85%",
    "3.731,61",
    "1018.9417",
    "Stk.",
    "iShsIII-Core MSCI World",
    "U.ETF",
    "Registered Shs USD",
    "(Acc) o.N.",
    "ISIN: IE00B4L5Y983",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Irland",
    "59,74",
    "30.12.2020",
    "55.067,78",
    "5.801,76",
    "10,54%",
    "60.869,54",
    "13.915",
    "Stk.",
    "iShsII-$Hgh Yld Corp Bd",
    "U.ETF",
    "Registered Shares o.N.",
    "ISIN: IE00B4PY7Y77",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Irland",
    "83,98",
    "30.12.2020",
    "1.217,57",
    "-48,96",
    "-4,02%",
    "1.168,61",
    "311.9589",
    "Stk.",
    "iShsV-EM Dividend",
    "UCITS ETF",
    "Registered Shares USD",
    "o.N.",
    "ISIN: IE00B652H904",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Irland",
    "16,62",
    "30.12.2020",
    "4.671,00",
    "512,51",
    "10,97%",
    "5.183,51",
    "70.6956",
    "Stk.",
    "iShs Global Corp Bd",
    "UCITS ETF",
    "Registered Shares USD",
    "o.N.",
    "ISIN: IE00B7J7TB45",
    "Wertpapierrechnung in",
    "Deutschland",
    "Lagerland: Irland",
    "88,91",
    "30.12.2020",
    "6.419,14",
    "-133,59",
    "-2,08%",
    "6.285,55",
    "ANZAHL POSITIONEN: 14",
    "SUMME KURSWERTE: 141489.6 EUR",
    "Bitte beachte:",
    "Soweit Kursangaben fehlen, handelt es sich entweder um Wertpapiere, für die ein Kurs nicht oder nicht",
    "rechtzeitig festgestellt werden konnte oder um nicht notierte Wertpapiere. Eine Gewähr für die Richtigkeit der",
    "Kurse können wir nicht übernehmen. In der Gewinn / Verlust-Rechnung sind steuerliche Aspekte nicht",
    "berücksichtigt.",
    "Bruchstücke aus ETF-Sparplänen werden in Wertpapierrechnung in Deutschland verwahrt."
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

### PR DESCRIPTION
**Pull request by dredav**
- Add testcase from #1188
- Fix #1188: Now we can parse the changed number format and also that sometimes the number of shares are above the line `Stk.`
- Quarter statement will now be parsed as `TransferIn` instead of `Buy` because we don't have a real buy price and the buy date.
- Fix #1343

### CODE REVIEW

File: src/brokers/traderepublic.js [hunk 1]
```diff
@@ -226,7 +226,21 @@ const parsePositionAsActivity = (content, startLineNumber) => {
...
+    numberOfSharesLine = content[startLineNumber].split(' ')[0];
+  } else {
+    // But sometimes before:
+    // 61.1149
+    // Stk.
+    numberOfSharesLine = content[startLineNumber - 1];
+  }
+
+  // In the Q4 2020 document the number format has changed (once?) from the german one to the english one. We simply replace the dot with a comma.
+  const numberOfShares = parseGermanNum(numberOfSharesLine.replace('.', ','));
```
Comment (SirGibihm) [inline src/brokers/traderepublic.js:242]: I do think this is a bad idea for the following reason:
If you cast this on a full German number format you will receive an illegitimate number:
`3.133,7` would become `3,133,7`. The testcases did not fail as there is no example where more than 1k stocks were listed. IMO we should implement a check wether the number contains a `.` and a `,` but this still leaves another issue: What about German round numbers: `1.337(,00)`. They would be parsed to equal `1,337`

**Review by SirGibihm — CHANGES_REQUESTED** [review]

File: src/brokers/traderepublic.js (hunk 1 above)
Comment (dredav) [reply src/brokers/traderepublic.js:242]: Yes, this part is a pretty bad solution. I've checked your samples and currently only one position has more than 999 shares: https://github.com/tresorone/tresor-import/blob/7c3a40a2370caa97eb782b970ad122eeedec6b91/tests/brokers/__mocks__/traderepublic/quarter_statement/2020_year_end_statement.json#L68

I will adjust this logic to be a little bit safer on the road:
- Check if `numberOfSharesLine` contains a `,`, then don't replace the `.`
- Add the 1000 shares position as an additional test case

**Review by SirGibihm — APPROVED** [review]
